### ISSUE TITLE
process is undefined

### ISSUE THREAD

**Issue by tanhauhau** [sveltejs/svelte-repl#105]
some library uses `process.env.NODE_ENV` to execute dev-only code.

<img width="1280" alt="Screenshot 2020-04-17 at 9 49 59 AM" src="https://user-images.githubusercontent.com/2338632/79523524-f870a800-8090-11ea-8ac2-baa5bd2a6628.png">

**Comment by qudo-lucas** [comment]
+1

**Comment by Rich-Harris** [comment]
closed via https://github.com/sveltejs/sites/pull/128
