### ISSUE TITLE
Help wanted, how can I implement this REPL into my own code?

### ISSUE THREAD

**Issue by AndreasHeintze** [sveltejs/svelte-repl#115]
Can anyone help me getting this Repl component to work? I have tried to install Sapper and then install this Repl component into that, but that makes the server crash as soon as I import it. I have tried it with just Svelte but then it says that I need plugins to import files that are not JavaScript. (codemirror.css)

What I really want is to make this REPL the base in a new client side component editor in a PHP platform we use. So we can use it to build Svelte components that is compiled into pure JS that is inserted into our PHP pages.

**Comment by Conduitry** [comment]
There are a couple of issues open about this sort of thing already. The short answer is that this isn't documented yet - and it should be, but we don't need another issue about it.

**Comment by Conduitry** [comment]
I see one of the duplicate issues, #88, was opened by you. Please don't do that.

**Comment by AndreasHeintze** [comment]
Ok, but when is the documentation coming? This is of no use without it.
