### ISSUE TITLE
Alert if repl hasn't been saved

### ISSUE THREAD

**Issue by lwkchan** [sveltejs/svelte-repl#117]
This is a feature request

I have a habit of closing tabs or windows by mistake and losing work, and others probably do too. It would be awesome if when the user closes the tab or leaves the page, that an alert is shown warning that the repl has not been saved. Perhaps a message like

```
Warning: this repl has not been saved and leaving will lose the most recent changes since last saving
```

If the user closes the message, immediately presses save, then leaves the page without making any other changes. Then this message won't be shown.

Happy to write the code and make a PR if this feature sounds like a good idea?

**Comment by irshadshalu** [comment]
Just came here to report this. Just lost 30 minutes worth of work because I hit a `Ctrl + R` for `Ctrl + T`

**Comment by vrde** [comment]
Same here, I just lost quite some work because I accidentally hit the browser *back* button :disappointed:.

**Comment by geoffrich** [comment]
I'd love to see this too. I believe CodePen does something similar.
