### ISSUE TITLE
odd little planet symbol when dragging

### ISSUE THREAD

**Issue by weepy** [sveltejs/svelte-repl#120]
I've not seen this in another webpage, but on the online REPL I sometimes see this little planet when I drag a div.

It sometimes occurs here => https://svelte.dev/repl/d3e73fcd45ff4d439420122d5a41c5b4?version=3.23.2

I'm not sure how to make it happen every time, but it seems to be something to do with draggables.

Any idea what it might be ?

**Comment by antony** [comment]
Do you mean a `no-entry` cursor?

**Comment by Conduitry** [comment]
I would assume this is referring to the `no-entry` cursor, and I would also assume that this is also the result of whatever components you're running not fully handling the drag-and-drop stuff.

**Comment by weepy** [comment]
It’s a planet not a no entry sign.

I’ll try and take a picture.

**Comment by weepy** [comment]
It disappears when I let go so hard to debug !

**Comment by weepy** [comment]
it also lags the mouse ever so slightly - so it's not a cursor.

**Comment by weepy** [comment]
![IMG_1324](https://user-images.githubusercontent.com/820/84859904-f497dc80-b065-11ea-84fe-8e8cee21d5a5.jpg)

**Comment by weepy** [comment]
I think it's something to do with how google chrome handles dragging links

https://stackoverflow.com/questions/6771196/stopping-chrome-from-changing-cursor-to-a-globe-while-dragging-a-link

a couple of preventDefault seems to have squashed it.
