### ISSUE TITLE
Update in-browser bundling to use newer Rollup version

### ISSUE THREAD

**Issue by Conduitry** [sveltejs/svelte-repl#122]
To suppose newer language features in the compiled code (like `??` and `?.`) we need to update the version of Rollup used for the in-browser bundling. This might be as easy as just upgrading the version we're using, but there might have been some relevant breaking changes from v1 -> v2 in terms of how we're programmatically calling it in the browser.

**Comment by dimfeld** [comment]
I've been running the REPL with rollup v2 on my personal website and it works fine. Aside from dependency updates, this was the only change necessary to make it work: https://github.com/dimfeld/svelte-repl/commit/f7cf7cf5e0bad0d95107f0e3d5d9a5b735ac0ce9
