### ISSUE TITLE
Wrapping of buttons in .app-controls

### ISSUE THREAD

**Issue by Wolfr** [sveltejs/svelte-repl#127]
Buttons don't appear on the same line in Safari Mobile:

![image](https://user-images.githubusercontent.com/12690/87665502-559af900-c767-11ea-947d-0dd079cc34dc.png)

This is especially apparent when viewing a REPL on iOS on an iPhone 8/iPhone SE.

Can be fixed by adding a rule of `white-space: nowrap` on `.app-controls`.

![image](https://user-images.githubusercontent.com/12690/87665509-5764bc80-c767-11ea-81b7-981cedbd4343.png)

I can't find the selector in the codebase, is this code in another repo?

**Comment by kevmodrome** [comment]
That part of the site is actually in the regular site, which is in the svelte repo: https://github.com/sveltejs/svelte/tree/master/site

**Comment by Wolfr** [comment]
Right. I figured it would be something like this. Thanks @kevmodrome . I will do a PR there.
