### ISSUE TITLE
Suggestion: use 'npx' and add 'svelte', rollup plugins etc to package.json

### ISSUE THREAD

**Issue by mikemaccana** [sveltejs/svelte-repl#13]
In the downloads, making the `scripts` in `package.json` use `npx`:

```
"scripts": {
    "build": "npx rollup -c",
    "autobuild": "npx rollup -c -w",
```

And including all the relevant rollup plugins in `package.json` would make using the `zip` files easier. This way `npm i` would install all the required packages locally and let people get started faster.

**Comment by Rich-Harris** [comment]
I don't understand — running a Node script puts `node_modules/.bin` into your `$PATH`, so you don't need `npx`. What am I missing?

The relevant plugins are already in the [project template](https://github.com/sveltejs/template/blob/master/package.json) you get when you download from the REPL, no?

**Comment by mikemaccana** [comment]
> running a Node script puts node_modules/.bin into your $PATH

You're right Rich, I didn't realise that -sorry for wasting your time!
