### ISSUE TITLE
Trouble importing geonames.js in REPL

### ISSUE THREAD

**Issue by LaughingBubba** [sveltejs/svelte-repl#134]
Hi, when I add this declaration in the REPL
```javascript
import Geonames from './geonames.js'
```
I get this as a warning message at the bottom of the REPL:

```Could not load https://unpkg.com/https@1.0.0/index.js (imported by https://unpkg.com/axios@0.20.0/lib/adapters/http.js): Cannot find "/index.js" in https@1.0.0```

Is this an issue with the REPL or the package itself?

**Comment by Conduitry** [comment]
Presumably the package. Something it trying to use the Node.js built-in module `https`, which doesn't exist on the browser, and is instead getting the empty package https://www.npmjs.com/package/https

In the browser, you should avoid using `axios` for doing network requests, as it's bloated, designed for the server, and doesn't do much that the browser's own `fetch` API doesn't.
