### ISSUE TITLE
Can't use Repl component in new svelte project

### ISSUE THREAD

**Issue by luucvanderzee** [sveltejs/svelte-repl#143]
## System info

Ubuntu 20.04
Node version 10.19.0
npm version 6.14.4

## The bug

To reproduce, run following commands:

```
npx degit sveltejs/template repl-test
cd repl-test
npm install
npm install @sveltejs/svelte-repl
```

Add the following line to `src/App.svelte`:

```
import Repl from '@sveltejs/svelte-repl'
```

Run the following command:

```
npm run dev
```

This yields the following error:

```
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
node_modules/@sveltejs/svelte-repl/src/codemirror.css (3:0)
1: /* BASICS */
2: 
3: .CodeMirror {
   ^
4:   /* copied colors over from prism */
5:   --background: var(--back-light);
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (/hdd/Projects/js/svelte/repl-test/node_modules/rollup/dist/shared/rollup.js:5252:30)
    at Module.error (/hdd/Projects/js/svelte/repl-test/node_modules/rollup/dist/shared/rollup.js:9811:16)
    at tryParse (/hdd/Projects/js/svelte/repl-test/node_modules/rollup/dist/shared/rollup.js:9692:23)
    at Module.setSource (/hdd/Projects/js/svelte/repl-test/node_modules/rollup/dist/shared/rollup.js:10118:19)
    at ModuleLoader.addModuleSource (/hdd/Projects/js/svelte/repl-test/node_modules/rollup/dist/shared/rollup.js:18279:20)
```
How can I get this to work? I checked the [rollup config](https://github.com/sveltejs/svelte/blob/master/site/rollup.config.js) of the Svelte site where this Repl component is used, but I did not see any plugins for loading css.

Thanks in advance!

**Comment by luucvanderzee** [comment]
Closing because I already found an answer in #118

**Comment by cglacet** [comment]
Could you please share your solution? I can't manage to find the answer in the other thread. 

I've tried something like: 

```
<script>
    import Repl from '../node_modules/@sveltejs/svelte-repl/src/Repl.svelte';
</script>

<Repl/>
```

But I get the same error as you did.

**Comment by FractalHQ** [comment]
I also can't manage to get Hackapes demo to start.  I've been trying to get a repl running for my own projects for months to no avail.

**Comment by quantuminformation** [comment]
@cglacet any luck?

**Comment by quantuminformation** [comment]
the error I get following OP is

```
[!] Error: UMD and IIFE output formats are not supported for code-splitting builds.
Error: UMD and IIFE output formats are not supported for code-splitting builds.
    at error (/Users/nikos/WebstormProjects/repl/client/repl-test/node_modules/rollup/dist/shared/rollup.js:5265:30)
```

**Comment by cglacet** [comment]
@quantuminformation Sadly I just tested that in a dirty way and only used git later so I have no history over my modifications, but I think I had to change [rollup.config.js](https://github.com/cglacet/svelte-pyodide/blob/master/front_office/svelte-app/rollup.config.js)

**Comment by dimfeld** [comment]
Yes, the REPL uses a dynamic import of CodeMirror, so your rollup config has to support code splitting. If you don't need compatibility with old browsers you can just set the output format to `es`. (see https://rollupjs.org/guide/en/#outputformat and https://rollupjs.org/guide/en/#code-splitting)

If you do need compatibility with older browsers then this sample Rollup project should show you how to adapt your rollup config and HTML template: https://github.com/rollup/rollup-starter-code-splitting
