### ISSUE TITLE
Removing a saved REPL from https://svelte.dev/apps

### ISSUE THREAD

**Issue by lukaszpolowczyk** [sveltejs/svelte-repl#153]
Specifically: I have a few random duplicates (forks) that do not differ in anything, but they cannot be deleted from https://svelte.dev/apps.
Will there be an option to remove a saved REPL?

**Comment by Conduitry** [comment]
Probably eventually. Duplicate of https://github.com/sveltejs/svelte/issues/3457

**Comment by lukaszpolowczyk** [comment]
@Conduitry It's a different repo. : /
Move issue to svelte-repl there, because I only looked in svelte-repl before adding the post.

**Comment by antony** [comment]
@lukaszpolowczyk the repl project doesn't deal with persisting, that is handled by the svelte site which lives inside the `svelte` repo, hence why the issue belongs there.
