### ISSUE TITLE
When typing on mobile, some stuff disappears after typing

### ISSUE THREAD

**Issue by TheOnlyTails** [sveltejs/svelte-repl#182]
When I'm trying to edit code with the REPL on mobile and trying to, for example, add a new variable, this happens:
[I'm typing "let", but once I add a space, the whole word is gone](https://user-images.githubusercontent.com/65342367/136713660-e747c6e2-68c5-4453-80ff-0b4b4acd857d.mp4)

**Comment by Conduitry** [comment]
CodeMirror (the editor library) is known not to work well on mobile browsers, and there have been several issues about this.  The next version of it, still in progress and not yet published on npm, should behave better.
