### ISSUE TITLE
v3 Svelte components loaded from npm fail to initialize properly in the REPL.

### ISSUE THREAD

**Issue by saabi** [sveltejs/svelte-repl#2]
I published svelte-image-encoder to npm: https://www.npmjs.com/package/svelte-image-encoder

When I try to update the v3 REPL to use the npm package instead of the file in the Gist, it gives me a runtime error for a `bind:this={element}` directive inside `onMount()`,  `element` being undefined when it runs. However the demo builds and runs well with a local Sapper/Rollup setup when using the npm installed package.

I think it might have to do with `index.js` or `index.mjs` being built differently.

For a quick reproduction replace `import ImgEncoder from './ImgEncoder.svelte';` with `import ImgEncoder from 'svelte-image-encoder';` in `App.js` in [this demo](https://v3.svelte.technology/repl?version=3.0.0-beta.23&gist=cb1ec0dcc5dfaa1e0de3844f3e7348d6).

Suggested so far on Discord:
> **Conduitry**: My initial thought is to try to build the `pkg.svelte` resolution rules into the REPL. I don't know how much trouble that would be
> **rich_harris**: maybe not terrible. would just mean we'd have to get `https://unpkg.com/[package-name]/package.json` and inspect it before fetching from `bundle.run`

**Comment by Conduitry** [comment]
The REPL does now have fancier module resolution and bundles everything in the browser - meaning, among other things, that it now supports `pkg.svelte`. The v3.svelte.technology redirect is broken right now, but if you go to https://svelte.dev/repl/cb1ec0dcc5dfaa1e0de3844f3e7348d6 and switch to the imported version of the component, everything looks fine to me. Closing.
