### ISSUE TITLE
Feature Request: Fork/Copy directly into Github

### ISSUE THREAD

**Issue by cstroliadavis** [sveltejs/svelte-repl#26]
It would be really useful if I could take a REPL I've created and instead of downloading it, if I could just fork it, or copy it directly to my github account.

**Comment by lukeed** [comment]
This reads more like a consumer-level integration. 

The website uses this component and does something with the contents. We used to read/write into GitHub gists but this had its own share of issues.

If you were to use this, you can look at how the REPL on the website is handling save/fork actions: https://github.com/sveltejs/svelte/blob/master/site/src/routes/repl/%5Bid%5D/_components/AppControls/index.svelte

**Comment by Conduitry** [comment]
Yep something like this (which does seem like a plausible addition) would be implemented in the main site's repo.
