### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by timeshift92** [sveltejs/svelte-repl#33]

**Comment by umanghome** [comment]
Were you able to figure this out?

**Comment by antony** [comment]
@umanghome we are able to help you over in https://svelte.dev/chat - not here.

**Comment by donnisnoni95** [comment]
Please see README.MD or go to http://svelte.dev/repl/

**Comment by umanghome** [comment]
Thought this is supposed to be a standalone app.

**Comment by matths** [comment]
> This is the guts of https://svelte.dev/repl, extracted into its own package so that it can be used elsewhere.

I thought that as well, so a basic description how to use this component would be much appreciated.
