### ISSUE TITLE
Reserved tab name "App" causes issues

### ISSUE THREAD

**Issue by loilo** [sveltejs/svelte-repl#36]
1. Create a new tab.
2. Try to name it "Append".
3. Note how after typing "App", the input field loses focus and the new tab is no longer deleteable nor renameable.

I assume this is due to the name state updating with each `input` event. Possible solutions would include only updating the name on `blur` or not identifying the "main" tab by its name (but instead, for example, by its index).

**Comment by donnisnoni95** [comment]
@loilo Thank you,, Are you already try this and maybe give a feedback.. maybe just using my fork repo

I still learning ... ☺️

**Comment by tanhauhau** [comment]
Fixed.
