### ISSUE TITLE
Solve the halting problem

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/svelte-repl#40]
it's really annoying when you're in the middle of typing a for loop...

```js
for (let i = 0; i < things.length; <cursor>)
```

...and the code starts running before you have a chance to write `i += 1`. Similarly if you're trying to write this...

```js
while (true) {
  // some code...
  if (someConditionIsMet()) break;
}
```

...you will get as far as `while (true) {`, it will add the closing `}`, and you're screwed.

Maybe not the easiest thing to fix, and certainly not in a general way, but I wonder if there's *something* that can be done to handle common cases. Like, idk, not running the code if the cursor is currently inside a loop?

**Comment by dkondrad** [comment]
Maybe a mode (like JSFiddle) where it doesn't re-parse / execute until you tell it to?

**Comment by practicalRope** [comment]
Maybe a floating button inline that lets you "merge" the last written code so it doesn't evaluate anything before you are done typing things?
This could be expanded upon to mean all code and not just loops.
If it's really that important to get that super instant feedback, could a shortcut for the "merging" functionality suffice?

**Comment by pngwn** [comment]
If we decide to disable running when the cursor is inside the loop what if you make a genuine mistake but don't move your cursor? Then you have no feedback at all and you might not know what you've done wrong immediately. Maybe we can provide a REPL specific error to provide the required feedback.

**Comment by donnisnoni95** [comment]
Maybe this could solve ? 👉 [JSBin/loop-protect](https://github.com/jsbin/loop-protect/)

**Comment by donnisnoni95** [comment]
@Rich-Harris , Maybe this could solve ? See 👉 [JSBin/loop-protect](https://github.com/jsbin/loop-protect/)

**Comment by donnisnoni95** [comment]
Ya... exactly... that is what i mean... i read the source code.. its too complex for me,, maybe we can simplify that... are you working on it now @Conduitry  ??

**Comment by weepy** [comment]
Could you just prevent instant reload if the cursor is within a loop parentheses?

**Comment by mustafa0x** [comment]
#55 (`handle_change` should be debounced) could help with this — you would just have to keep typing within the debounce timeout (200ms or so).
