### ISSUE TITLE
options.name should be capitalised (index.svelte)

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/svelte-repl#45]
This warning appears on the Svelte GL demo app: https://svelte.dev/repl/ce2efb3fd43240fb9773c93367d25d9f?version=3.9.1

![Screen Shot 2019-09-03 at 15 56 24](https://user-images.githubusercontent.com/1162160/64204270-69957f00-ce63-11e9-9ed3-9041adf4581d.png)

I *think* it should just be a case of not passing `options.name` and letting the default logic do its thing

**Comment by brettz9** [comment]
I came across this in the demo at https://svelte.dev/tutorial/making-an-app by simply adding a tab to create a bare component "abc.svelte" (one just containing `<b>hi</b>`) and importing it with:

```svelte
<script>
import App from './abc.svelte';

const app = new App({
	target: document.body
});

</script>

<h1>What now?</h1>
```

**Comment by Wolfr** [comment]
Same error if you try import an svg as `@html`.

```
<svg>
	<g>
		<rect width="400" height="400" fill="black"></rect>
	</g>
</svg>

```

**Comment by dravog7** [comment]
I got the same error on the tutorial

when I tried to do the same offline after downloading the template using 

`npx degit sveltejs/template my-svelte-project`

and added about.svelte
![Screenshot from 2020-03-02 12-37-33](https://user-images.githubusercontent.com/31211464/75653073-bb885780-5c82-11ea-93ff-c7c6ffd37db7.png)

The result was 
![Screenshot from 2020-03-02 12-48-22](https://user-images.githubusercontent.com/31211464/75653123-de1a7080-5c82-11ea-8b79-e7b7f62b244d.png)

I was able to fix this by changing the name of the import from 

`import about from 'about.svelte'` to `import About from 'about.svelte'`

Would be helpful if a warning was given for this issue.

**Comment by Parables** [comment]
@dravog7  I also had this error on RELP when a created a tab and named it as `state.svelte`. 
Fixed it by changing it to `State.svelte`. Thanks for sharing :+1:  :heart:
