### ISSUE TITLE
Unable to import from packages beginning with "@"

### ISSUE THREAD

**Issue by hperrin** [sveltejs/svelte-repl#46]
Trying to import from a package whose name begins with "@" results in an error:

```
Error: Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)
```

For example:

```
<script>
	import {MDCCheckbox} from '@material/checkbox';
</script>
```

Will throw that error.

**Comment by Conduitry** [comment]
I can't reproduce this with an App.svelte containing only that `<script>` block.

**Comment by hperrin** [comment]
This was actually caused by my own code, so my bad.
