### ISSUE TITLE
`handle_change` should be debounced

### ISSUE THREAD

**Issue by mustafa0x** [sveltejs/svelte-repl#55]
During typing, even quickly, many error messages appear, packages are reloaded, etc — all which is very distracting. This issue can be ameliorated with a debouncer.

https://github.com/sveltejs/svelte-repl/blob/master/src/Repl.svelte#L126

```js
function debounce(fn, timeout) {
    let timeout_id;
    return (...args) => {
        clearTimeout(timeout_id);
        timeout_id = setTimeout(() => fn(...args), timeout);
    };
}
```

**Comment by Rich-Harris** [comment]
Belated thanks — closing in favour of https://github.com/sveltejs/sites/pull/130 and https://github.com/sveltejs/sites/pull/131
