### ISSUE TITLE
What about auth?

### ISSUE THREAD

**Issue by KeyJoo** [sveltejs/svelte-repl#6]
# About auth

Hi. I was logged to https://svelte.dev/repl & change some code, save it. But I can't find list of my saved codes.

**Question**
> Can I save code for open in future sessions?

What I do wrong?

## Press F5 & get failed to fetch
![Screenshot_2019-04-23_19-29-54](https://user-images.githubusercontent.com/21124057/56599187-bbe5aa00-65fe-11e9-8d97-d49a64f204f0.png)

- [ ] :penguin: Is it possible to do REPL (online tool), like codepen & etc ?..

**Comment by Conduitry** [comment]
There's now an issue in the Svelte repo https://github.com/sveltejs/svelte/issues/3019 for having a list of saved REPLs. This code in this repo isn't actually responsible for saving or loading the REPL contents.
