### ISSUE TITLE
REPL - console.dir() and console.group()/groupEnd() support

### ISSUE THREAD

**Issue by rlaferla** [sveltejs/svelte-repl#68]
It would be really helpful if the REPL console could support console.dir(), console.group()/groupEnd().

**Comment by Danny-Engelman** [comment]
all 3 console methods work (in 3.15.0 at least)

**Comment by rlaferla** [comment]
`console.dir()` works but the `console.group/groupEnd` do not even under 3.16

https://svelte.dev/repl/5ee171d2febb4eff9c9110c9aad2dfc5?version=3.16.0

**Comment by Danny-Engelman** [comment]
FYI, Your REPL in my console:

![](https://i.imgur.com/lqhRgFs.jpg)

**Comment by rlaferla** [comment]
Which browser are you using?  Does it work for you across different browsers?  I just tried Chrome and Safari on macOS and neither worked.
![image](https://user-images.githubusercontent.com/1135694/71202305-eeb57000-2269-11ea-957e-a4a034a5216d.png)

**Comment by rlaferla** [comment]
I also tried the latest Svelte REPL, 3.16.5.

https://svelte.dev/repl/hello-world?version=3.16.5

**Comment by Danny-Engelman** [comment]
Your REPL: https://svelte.dev/repl/5ee171d2febb4eff9c9110c9aad2dfc5

in:

### Firefox (windows)

![](https://i.imgur.com/KIAXmRl.jpg)

### Chrome (windows)

![](https://i.imgur.com/sqwpWiC.jpg)

### Opera (windows)

![](https://i.imgur.com/ATUTmBM.jpg)

So the REPL does support ``console.dir(), console.group()/groupEnd()``

So something in your Browser(s) is blocking those functions

* Disable all extensions
* try private mode
* etc. etc.

**Comment by Conduitry** [comment]
Is there a confusion between the browser's native console and the 'Console' section that appears in the lower right within the REPL itself?

**Comment by Danny-Engelman** [comment]
> Is there a confusion between the browser's native console and the 'Console' section that appears in the lower right within the REPL itself?

You are 100% correct, the REPL console seems to be a wrapper around the browsers console, and as OP stated some of the default console methods are not wrapped/implemented.

I have built a REPL Browser Extension which outputs things like global search to the Browser console... so never use the REPL console. Sorry for the confusion...
