### ISSUE TITLE
CDN caching prevents gist updates from being seen

### ISSUE THREAD

**Issue by btakita** [sveltejs/svelte-repl#7]
To reproduce, visit a repl gist, then edit the gist, then reload.

Notice the HTTP response header:

`cf-cache-status: HIT`

![svelte-repl-cdn-issue](https://user-images.githubusercontent.com/3664/56622131-f2222a00-65fc-11e9-870c-1d4816ad5d63.png)

**Comment by Conduitry** [comment]
I'm hoping we can add some headers to the gist endpoint that can make Cloudflare cache its responses less aggressively or not at all - If we can, that would be something that would happen in the main Svelte site repo, not here.

**Comment by lukeed** [comment]
I just sent Rich a message to fix this issue. Was my fault – deployment misconfig.

**Comment by Rich-Harris** [comment]
It categorically was *not* Luke's fault, but he helped fix it anyway — should be good now hopefully

**Comment by lukeed** [comment]
It sure was. It's been fixed, seeing it on my end. You should be able to update your gists soon @btakita, if not already 👍 

<img width="412" alt="Screen Shot 2019-04-23 at 4 39 02 PM" src="https://user-images.githubusercontent.com/5855893/56622836-7d43f580-65e6-11e9-91a1-5a25fc45b14f.png">
