### ISSUE TITLE
Support markdown files in REPL

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/svelte-repl#73]
Could be really useful for documenting distributed components, etc. Might pose some subtle UI challenges

**Comment by tanhauhau** [comment]
markdown as svelte component?

**Comment by Conduitry** [comment]
Just static markdown that gets rendered to serve as documentation is how I had interpreted this.

**Comment by mjgartendev** [comment]
I was able to get something working by hacking with marked directly in `Output/index.svelte#register_output`,  but if I try to pull it out to a separate file or include any of the markdown utils (highlight, extract_frontmatter, etc) from site-kit things blow up.

![image](https://user-images.githubusercontent.com/32685677/73119354-3f358280-3f26-11ea-9a82-6e1fe1288f4f.png)

I'm not sure how to go about styling the output, handling the app download properly, or adding customization to the Renderer without making extensive changes, which shouldn't be necessary. But it does appear this would be very useful.

**Comment by tanhauhau** [comment]
that's an interesting progress @mjgartendev , do you have a branch so we can continue to work on it?

**Comment by mjgartendev** [comment]
@tanhauhau unfortunately I do not. The screenshot is from a local repl I use as a sandbox for quick experiments and I didn't think my solution was worth creating a pull request.

Here are the basic changes to get something functioning:

## `src/Input/ComponentSelector.svelte`
Add `md` to regex in the `closeEdit()` function so you can edit a file name to end with .md extension
```js
<script>
    function closeEdit() {
        const match = /(.+)\.(svelte|js|md)$/.exec($selected.name);
</script>
```

## `src/Output/index.svelte`  
```svelte
<script>
...
import marked from 'marked';
// Save the selected markdown file's source to a markdown variable
let markdown = '';

register_output({
    set: async (selected, options) => {
        // Add logic to catch when selected component from Input is a md file
	if (selected.type === 'md') {
	    js_editor.set(`/* Select a component to see its compiled code */`);
	    css_editor.set(`/* Select a component to see its compiled code */`);
            // return before trying to compile as a Svelte component.
	    return markdown = selected.source;			
        }
    ...
</script>

<!-- Add a tab to view md preview: -->
<div class="tab-content" class:visible={view === 'md'}>
	<div class="markdown">
		{@html marked(markdown)}
	</div>
</div>
```

I wasn't sure if you should you be able to dynamically create/select/edit markdown files using the module editor Input (each md file saved in the repl's components store) or just optionally render a static README.md file for each gist. 

I believe the solution to each case would be entirely different.
