### ISSUE TITLE
Wrong array contents displayed in REPL Console pane

### ISSUE THREAD

**Issue by iovuio** [sveltejs/svelte-repl#80]
**Steps to reproduce**

1. Open repl https://svelte.dev/repl/b3be31da940b4d50b6216283fd04cacc?version=3.16.7
2. Resize Console pane so that log contents are visible.
3. In the result view check the provided checkbox. 

**Expected results**
When value under checkbox (bound value) changed, the new contents of the array displayed in the Console Pane due to `$: console.log` call

**Actual results**
The array contents are logged, however the contents are wrong (when value is true, value logged is false)

**Comment by iovuio** [comment]
Tested in latest Chrome and Firefox beta.

**Comment by luisjakon** [comment]
Looks like in the example above you are tracking changes to the array reference itself which does not change even when its contents change...

Try tracking the changes this way to see the difference:
```JS
$: console.log(arr[0])
```

**Comment by iovuio** [comment]
@luisjakon,

Thank you for your reply.

Please note that the issue described is not reproducible outside the REPL.
It looks to me as a problem in the REPL console only.

I am attaching a dummy project with the exact same contents which showcases the browser console correctly displays the contents of the array.

Run with `npm run dev`

Open browser with developer tools, go to Console tab.

Check/uncheck the checkbox on the page. -> Contents of array correctly displayed in the browser console.

[svelte-repl-iss-80-no-issue.zip](https://github.com/sveltejs/svelte-repl/files/4116497/svelte-repl-iss-80-no-issue.zip)

**Comment by luisjakon** [comment]
@iovuio I see.  It looks like the REPL console pane does not update properly when tracking the arr...but can do so properly when tracking arr[0]...

Could be a memoization problem of the pane and the array references...

**Comment by AlexxNB** [comment]
Confirm the bug in REPL's console.
I've [an example](https://svelte.dev/repl/adb0c1a000a44b88bd3e79df94ca6d49?version=3.19.1), where I have two-way binding and `console.log` in reactive statement. When I type 1,2,3,4... in the Input - REPL's console shows that object changed, but print old value. At same time browser's console shows object with new value each time.

![изображение](https://user-images.githubusercontent.com/10389013/75416789-5eb63580-5940-11ea-9288-d7cd1a4c6e7d.png)
