### ISSUE TITLE
Using dimension bindings causes REPL error (defaultView of null)

### ISSUE THREAD

**Issue by Wolfr** [sveltejs/svelte-repl#83]
When I use `bind:clientWidth` in the REPL I get this error:

```Error:
message: "Cannot read property 'defaultView' of null"
stack: TypeError: Cannot read property 'defaultView' of null
at HTMLObjectElement.object.onload (eval at handle_message (about:srcdoc:13:8), <anonymous>:81:42)
```

You can see the error in action in a simplified REPL here: https://svelte.dev/repl/e8001ba9ceb6438d88353da1db7bb19d?version=3.17.1

**Comment by Conduitry** [comment]
This is https://github.com/sveltejs/svelte/issues/2147
