### ISSUE TITLE
The default README.md contains strange UTF8 replacement characters

### ISSUE THREAD

**Issue by lovasoa** [sveltejs/svelte-repl#84]
When using the "download" feature of the REPL on svelte.dev (https://svelte.dev/repl/), it downloads a file called `svelte-app.zip`. At the root of the ZIP, there is a file called `README.md`. This file contains a sequence of bytes that is invalid in UTF8 : 

```
$ hexdump -C README.md 
00000000  2a 50 73 73 74 20 14 a0  6c 6f 6f 6b 69 6e 67 20  |*Psst ..looking |
00000010  66 6f 72 20 61 20 73 68  61 72 65 61 62 6c 65 20  |for a shareable |
```

(just after `Psst `, there is a `0x14 0xa0` byte sequence which is invalid)

**Comment by Conduitry** [comment]
Removed the non-ascii characters in https://github.com/sveltejs/template/commit/929052a297a4ee4b5c1a967fa9956328a0c1eb71 and am currently redeploying the site to pull the new version of the template into the REPL.

**Comment by lovasoa** [comment]
@Conduitry : Also, I noticed the same thing happens with non-ascii characters inside the source files themselves : 

<img width="705" alt="image" src="https://user-images.githubusercontent.com/552629/73616192-b8ad2f00-4610-11ea-929f-87a27b793f6d.png">


<img width="498" alt="image" src="https://user-images.githubusercontent.com/552629/73616200-c5318780-4610-11ea-972c-22a5b9b00823.png">
