### ISSUE TITLE
Error on importing packages with @

### ISSUE THREAD

**Issue by dritter** [sveltejs/svelte-repl#89]
Hi there!

When trying to import `@smui/select` I get the following error:
```
Error: Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)
```

Example (using the demo code from https://www.npmjs.com/package/@smui/select):
```HTML
<script>
  import Select, {Option} from '@smui/select';
 
  let fruits = ['Apple', 'Orange', 'Banana', 'Mango'];
  let fruitChoice = '';
</script> 
 
<Select bind:value={fruitChoice} label="Fruit">
  <Option value=""></Option>
  {#each fruits as fruit}
    <Option value={fruit} selected={fruitChoice === fruit}>{fruit}</Option>
  {/each}
</Select>
```

This seems related with #46 

// cc @hperrin

**Comment by antony** [comment]
Hi @dritter - this isn't a bug, it's to do with the way the REPL's bundling is configured. Importing CSS directly requires extra plugins, which the bundler doesn't have.

**Comment by dritter** [comment]
Ha! Thanks for clarification @antony
