### ISSUE TITLE
Repl Error - Unexpected token (Note that you need plugins to import files that are not JavaScript)

### ISSUE THREAD

**Issue by palerdot** [sveltejs/svelte-repl#91]
Hi,

I recently published a package [svelte-speedometer](https://github.com/palerdot/svelte-speedometer), which seem to work fine when I download the repl code locally and with `svelte storybook` but not in hosted `Svelte Repl`.

EDIT: The component is bootstrapped with official svelte component template - https://github.com/sveltejs/component-template

Repl Link where issue can be seen - https://svelte.dev/repl/cf869c9ab9f9431195222ba6cea10b59?version=3.20.1

I cloned the `svelte-repl` locally where things seem to be working fine. Link - https://github.com/palerdot/svelte-repl-issue-repro

The actual cloned zip file can be seen here in the repo - https://github.com/palerdot/svelte-repl-issue-repro/blob/master/svelte-app.zip

Source code - https://github.com/palerdot/svelte-speedometer

Storybook link where things seem to work - https://palerdot.in/svelte-speedometer

Any help on this is appreciated, as it seems there is already this [codesandbox issue](https://github.com/sveltejs/svelte/issues/2620) because of which codesandbox cannot be used to host svelte code. With Svelte REPL not working, it is difficult to share svelte snippets for this package.

Please let me know if any other information is needed from my end.

**Comment by tanhauhau** [comment]
I'm guessing could be this line 

```js
// src/core/config/index.js
import { calculateSegmentLabelCount } from "../util/"
```

instead of importing the folder, `../util/` try `../util/index.js`

**Comment by palerdot** [comment]
@tanhauhau but is valid JS right? This piece of code works fine almost everywhere (codesandbox snippets where this core logic is used for https://github.com/palerdot/react-d3-speedometer) ...  This is how I import all my files ... Is there any chance this will be fixed in `svelte repl`?

**Comment by palerdot** [comment]
Also, it is working fine locally ... The same `svelte-repl` when cloned locally is working fine ... just in the hosted version this is a problem ...

**Comment by antony** [comment]
@palerdot adding support for different filetypes and all sorts of bundler config isn't really the goal of the repl. It would be impossible to support every npm package out there, such as the fine grained control you get with rollup.
